Traceback (most recent call last):
  File "SAVED.exe", line 1037, in <module>
    with open(SAVED.txt) as f:
IOError: [Errno 2] No such file or directory: 'SAVED.txt'
	CRITICAL ERROR
